In [2]:
import numpy as np

arr = np.full((3, 3), True)
print("Câu 1:\n", arr)

arr_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr_2D = arr_1D.reshape(3, 3)
print("\nCâu 2 - arr_2D ban đầu:\n", arr_2D)

arr_2D[:, [0, 2]] = arr_2D[:, [2, 0]]
print("\nCâu 2 - sau đổi cột 1 và 3:\n", arr_2D)

arr_2D[[0, 1], :] = arr_2D[[1, 0], :]
print("\nCâu 3 - sau đổi dòng 1 và 2:\n", arr_2D)

arr_2D = arr_2D[::-1, :]
print("\nCâu 4 - đảo ngược dòng:\n", arr_2D)

arr_2D = arr_2D[:, ::-1]
print("\nCâu 5 - đảo ngược cột:\n", arr_2D)

arr_2D_null = np.array([[1, 2, 3], [np.nan, 5, 6], [7, np.nan, 9], [4, 5, 6]])
has_null = np.isnan(arr_2D_null).any()
print("\nCâu 6 - có giá trị null không?", has_null)

arr_2D_null[np.isnan(arr_2D_null)] = 0
print("\nCâu 7 - thay null bằng 0:\n", arr_2D_null)

Câu 1:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]

Câu 2 - arr_2D ban đầu:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Câu 2 - sau đổi cột 1 và 3:
 [[2 1 0]
 [5 4 3]
 [8 7 6]]

Câu 3 - sau đổi dòng 1 và 2:
 [[5 4 3]
 [2 1 0]
 [8 7 6]]

Câu 4 - đảo ngược dòng:
 [[8 7 6]
 [2 1 0]
 [5 4 3]]

Câu 5 - đảo ngược cột:
 [[6 7 8]
 [0 1 2]
 [3 4 5]]

Câu 6 - có giá trị null không? True

Câu 7 - thay null bằng 0:
 [[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]
